services:
  frontend:
    image: 'ghcr.io/${OWNER}/film_frontend:latest'
    environment:
      VITE_API_URL: /api/afisha
      VITE_CDN_URL: /content/afisha
    volumes:
      - frontend_volume:/app/dist

  backend:
    image: 'ghcr.io/${OWNER}/film_backend:latest'
    environment:
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DEBUG: '*'
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - webnet

  server:
    image: 'ghcr.io/${OWNER}/film_server:latest'
    ports:
      - '81:80'
    volumes:
      - frontend_volume:/var/www
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

  db:
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - webnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: your@email.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - webnet

volumes:
  postgres_data:
  frontend_volume:
  pgadmin-data:

networks:
  webnet:
