name: Build and Push Docker Image

on:
  push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: set lower case for owner
        run: |
          echo "REPO=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend docker
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:backend'
          push: true
          tags: 'ghcr.io/${{ env.REPO }}/film_backend:latest'
      
      - name: Build and push frontend docker
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:frontend'
          push: true
          tags: 'ghcr.io/${{ env.REPO }}/film_frontend:latest'

      - name: Build and push server docker
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:nginx'
          push: true
          tags: 'ghcr.io/${{ env.REPO }}/film_server:latest'
